name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git pull
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: 825148988@qq.com
          password: Test1234.
          logout: false

      - name: Use Skopeo Tools Sync Image to Docker Hub 1
        run: |
          skopeo copy docker://docker.io/library/openjdk:8-jdk-alpine docker://registry.cn-hangzhou.aliyuncs.com/wzj_hub/openjdk:8-jdk-alpine
        # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
